In [1]:
import pandas as pd

train_df = pd.read_csv("../data/processed/train_binary.csv")
test_df = pd.read_csv("../data/processed/test_binary.csv")

print(train_df.shape, test_df.shape)
train_df.head()

(286854, 3) (31873, 3)

                                                text     label         dataset
0  ürünü hepsiburadadan alalı 3 hafta oldu. orjin...  Positive  urun_yorumlari
1  ürünlerden çok memnunum, kesinlikle herkese ta...  Positive  urun_yorumlari
2      hızlı kargo, temiz alışveriş.teşekkür ederim.  Positive  urun_yorumlari
3  bu telefonu başlıca alma nedenlerim ise elimde...  Positive  urun_yorumlari
4  telefon gayet güzel ben kırmızı aldım baya şık...  Positive  urun_yorumlari

In [ ]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

train_df["label_num"] = (train_df["label"] == "Positive").astype(int)
test_df["label_num"] = (test_df["label"] == "Positive").astype(int)
train_df[["label", "label_num"]].head()

      label  label_num
0  Positive          1
1  Positive          1
2  Positive          1
3  Positive          1
4  Positive          1

In [6]:
X_train = train_df["text"]
y_train = train_df["label_num"]
X_test = test_df["text"]
y_test = test_df["label_num"]


pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=20000, ngram_range=(1, 2))),
    ("clf", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2))),
                ('clf',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [7]:
from sklearn.metrics import classification_report
y_pred = pipeline.predict(X_test)
print(classification_report(y_test,y_pred,target_names=["Negative","Positive"]))

              precision    recall  f1-score   support

    Negative       0.69      0.89      0.78      5656
    Positive       0.98      0.91      0.94     26217

    accuracy                           0.91     31873
   macro avg       0.83      0.90      0.86     31873
weighted avg       0.92      0.91      0.91     31873